// RN-compatible styles (camelCase, no boxShadow; use elevation on Android where needed)
export const styles = {
  frame: {
    width: 390,
    height: 844,
    borderRadius: 40,
    overflow: "hidden",
    position: "relative",
    backgroundColor: "#F7F8FA",
    display: "flex",
    flexDirection: "column",
    // boxShadow omitted for RN; use elevation on Android if needed
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 25 },
    shadowOpacity: 0.25,
    shadowRadius: 80,
  },
  statusBar: {
    height: 50,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingBottom: 4,
    paddingHorizontal: 24,
    fontSize: 14,
    fontWeight: "600",
    color: "#1a1a1a",
    backgroundColor: "#fff",
    flexShrink: 0,
  },
  topBar: {
    display: "flex",
    flexDirection: "row",
    alignSelf: "stretch",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingTop: 8,
    paddingBottom: 12,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F1F3",
    flexShrink: 0,
  },
  content: {
    flex: 1,
    overflow: "scroll",
  },
  bottomNav: {
    display: "flex",
    flexDirection: "row",
    alignSelf: "stretch",
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
    height: 82,
    paddingVertical: 6,
    paddingBottom: 20,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#F0F1F3",
    flexShrink: 0,
  },
  navItem: (active) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    paddingVertical: 4,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: active ? "#E8F5EE" : "transparent",
  }),
  navLabel: (active) => ({
    fontSize: 11,
    fontWeight: active ? "600" : "500",
    color: active ? "#1B6B4A" : "#94A3B8",
  }),
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#F0F1F3",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 10,
  },
  listItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#F5F6F8",
  },
  badge: (color) => ({
    display: "flex",
    alignSelf: "flex-start",
    alignItems: "center",
    paddingVertical: 3,
    paddingHorizontal: 10,
    borderRadius: 20,
    fontSize: 12,
    fontWeight: "600",
    backgroundColor: color + "15",
    color: color,
  }),
  tag: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: "500",
    backgroundColor: "#F0F1F3",
    color: "#64748B",
  },
  pill: (active) => ({
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    fontSize: 13,
    fontWeight: "500",
    backgroundColor: active ? "#1B6B4A" : "#F0F1F3",
    color: active ? "#fff" : "#64748B",
    whiteSpace: "nowrap",
  }),
  btn: (variant) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingVertical: variant === "sm" ? 8 : 14,
    paddingHorizontal: variant === "sm" ? 16 : 24,
    borderRadius: 12,
    fontSize: variant === "sm" ? 13 : 15,
    fontWeight: "600",
    backgroundColor: variant === "outline" ? "#fff" : "#1B6B4A",
    borderWidth: variant === "outline" ? 2 : 0,
    borderColor: variant === "outline" ? "#1B6B4A" : "transparent",
    width: variant === "sm" ? undefined : "100%",
    alignSelf: "stretch",
  }),
  avatar: (color, size = 40) => ({
    width: size,
    height: size,
    borderRadius: size / 2,
    backgroundColor: color,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  }),
  avatarText: (size = 40) => ({
    color: "#fff",
    fontSize: size * 0.4,
    fontWeight: "700",
  }),
  progressBarTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F0F1F3",
    position: "relative",
    overflow: "hidden",
  },
  progressBarFill: (pct, color) => ({
    position: "absolute",
    left: 0,
    top: 0,
    height: "100%",
    width: `${pct}%`,
    borderRadius: 3,
    backgroundColor: color,
  }),
  pageHeader: {
    paddingTop: 16,
    paddingBottom: 8,
    paddingHorizontal: 20,
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  subHeader: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    paddingVertical: 8,
    paddingTop: 8,
    paddingBottom: 12,
    paddingHorizontal: 20,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#F0F1F3",
  },
};
